apiVersion: v1
kind: Secret
metadata:
  name: oasis-secrets
  namespace: biblioteca-oasis
type: Opaque
stringData:
  # Reemplazar con tus credenciales reales de Cloud SQL
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_NAME: "oasis"
  JWT_SECRET: "bibliotecaOasisSecretKey2026IntegracionServiciosCloudGCPUTP"
